apiVersion: v1
kind: ServiceAccount
metadata:
  name: nfs-client-provisioner
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nfs-client-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: data.nas
            - name: NFS_SERVER
              value: 192.168.43.103
            - name: NFS_PATH
              value: /home/xshrim/data/nas
      #imagePullSecrets:
      #  - name: ebpaas-registry-20.20
      volumes:
        - name: nfs-client-root
          nfs:
            server: 192.168.43.103
            path: /home/xshrim/data/nas
